# -*- coding: utf-8 -*-
"""Day_1_project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12uWNYOJmSUY3a9Y8qquuIVB3A7YJMexz
"""

def rectangle(legnth, width):
  rec_area = legnth * width
  rec_perimeter = 2 * legnth + 2 * width
  return f'The area is {rec_area}, and the perimeter is {rec_perimeter}'

def triangle_area(base, height):
  tri_area = base * height /2
  return f'The area is {tri_area}.'

def triangle_perimeter(side_1, side_2, side_3):
  tri_perimeter = side_1 + side_2 + side_3
  return f'The perimeter is {tri_perimeter}.'

def cube(legnth):
  cube_area = legnth ** 3
  cube_surface_area = 6 * legnth ** 2
  return f'The area is {cube_area}, and the perimeter is {cube_surface_area}.'

def circle(radius):
  circ_diamater = radius * 2
  circ_circumferance = 2 * 3.14 * radius
  circ_area = 3.14 * radius ** 2
  return f'The diamater is {circ_diamater}, the circumferance is {circ_circumferance}, and the area is {circ_area}.'