# -*- coding: utf-8 -*-
"""Geometric_calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zr6TgbAkiLX8KXeCYjCPQyd6TDI6jUEM

'''
This is a geometic calculator. It will ask you for the numer needed and then return an answer with the area, perimeter, 
surface area, ect. To solve a shape run all the cells then in the bottom cell and then put in the valuse when prompted. The shapes it can 
solve are circle, cone, cylinder, triangle, rectangle, cube, rectangular prisim and a pyramid. Type stop if you don't want any more shape/solutions. If you want a reminder of what the shapes are type anything that isn't a name of one of the shapes.
'''
"""

import math
import numpy as np

"""##Formulas """

class Circle():
  def __int__(self):
    pass

  def circle(self, radius):
    self.radius = radius
    circ_diamater = radius * 2
    circ_circumferance = 2 * 3.1415 * radius
    circ_area = 3.1415 * radius ** 2
    return f'The diamater is {circ_diamater}, the circumferance is {circ_circumferance}, and the area is {circ_area}.'

  def cone (radius, height):
    cone_slant = math.sqrt( radius ** 2 + height ** 2)
    cone_surface_area = 3.1415 * radius * (radius + cone_slant)
    cone_volume = 3.1415 * radius ** 2 * height / 3
    cone_area = 3.1415 * radius ** 2
    cone_circumferance = 2 * 3.1415 * radius
    return f'The area of the base is {cone_area}, and the circumferance of the base is {cone_circumferance}.\n The surface area of the cone is {cone_surface_area}, the volume of the cone is {cone_volume},\n and the slant is {cone_slant}.'

  def cylinder(radius, height):
    cyl_surface_area = 2 * radius * 3.1415 * height + 2 * 3.1415 * radius ** 2
    cyl_volume = 3.1415 * radius ** 2 * height
    cyl_lateral_surface = 2 * 3.1415 * radius * height
    cyl_base_area = 3.1415 * radius ** 2
    cyl_diameter = 2 * radius
    return f'The diameter is {cyl_diameter}, and the base area is {cyl_base_area}. The volume is {cyl_volume},\n the surface area is {cyl_surface_area}, and the lateral surface is {cyl_lateral_surface}.'

class Triangle():
  def __int__(self):
    pass

  def area(self, base, height):
    self.base = base
    self.height = height
    area = self.base * self.height /2
    return f'The area is {area}.'
    
  def perimeter(self, side_1, side_2, side_3):
    self.side_1 = side_1
    self.side_2 = side_2
    self.side_3 = side_3
    perimeter = side_1 + side_2 + side_3
    return f'The perimeter is {perimeter}.'

class Rectangles():
  def __int__(self):
    pass

  def rectangle(self, length, width):
    rec_area = (length * width)
    rec_perimeter = 2 * length + 2 * width
    return f'The area is {rec_area}, and the perimeter is {rec_perimeter}'

  def cube(self, length):
    self.length = length
    cube_area = length ** 3
    cube_surface_area = 6 * length ** 2
    return f'The volume is {cube_area}, and the surface area is {cube_surface_area}.'

  def rectangular_prism(self, length, width, height):
    self.length = length
    self.width = width
    self.height = height
    recp_surface_area = 2 * (length * width + length * height + height * width)
    recp_volume = width * length * height
    recp_space_diagonal = math.sqrt(length ** 2 + width ** 2 + height ** 2)
    return f'The surface area is {recp_surface_area}, the volume is {recp_volume}, and the space diagonal is {recp_space_diagonal}.'

  def pyramid(self, width, length, height):
    self.length = length
    self.width = width
    self.height = height
    w = width 
    l = length
    h = height
    pyr_surface_area = l * w + l * math.sqrt((w / 2) ** 2 + h ** 2 + w) * math.sqrt((l / 2) ** 2 + h ** 2)
    pyr_volume = l * w * h / 3
    pyr_lateral_surface_area = l * math.sqrt((w / 2) ** 2 + h ** 2 + w) * math.sqrt ((l / 2) ** 2 + h ** 2)
    pyr_base_area = l * w
    return f'The base area is {pyr_base_area}. The surface area is {pyr_surface_area}, the lateral surface area is {pyr_lateral_surface_area}, and the volume is {pyr_volume}.'

x = x
while x != 'stop':
  x = str(input("\nWhat shape do you want to solve?\n"))
  if x.lower() == 'rectangle':
    l = input("What is the length?\n")
    w = input("What is the width?\n")
    l = int(l)
    w = int(w)
    x = Rectangles()
    print(x.rectangle(l, w))
  elif x.lower() == 'triangle':
    y = input('Do you want to find the area, perimeter, or both?\n')
    if y.lower() == 'area':
      b = input('What is the legnth of the base?\n')
      h = input('What is the height?\n')
      b = int(b)
      h = int(h)
      t = Triangle()
      print(t.area(b, h))
    if y.lower() == 'perimeter':
      s_1 = input('What is the legnth of side 1?\n')
      s_2 = input('What is the legnth of side 2?\n')
      s_3 = input('What is the legnth of side 3?\n')
      s_1 = int(s_1)
      s_2 = int(s_2)
      s_3 = int(s_3)
      t = Triangle()
      print(t.perimeter(s_1, s_2, s_3))
    if y.lower() == 'both':
      b = input('What is the base?\n')
      h = input('What is the height?\n')
      s_1 = input('What is the legnth of side 1?\n')
      s_2 = input('What is the legnth of side 2?\n')
      s_3 = input('What is the legnth of side 3?\n')
      s_1 = int(s_1)
      s_2 = int(s_2)
      s_3 = int(s_3)
      b = int(b)
      h = int(h)
      y = Triangle()
      print(y.perimeter(s_1, s_2, s_3), y.area(b, h))
    else:
      print('Please enter area, primeter, or both.\n')
  elif x.lower() == 'circle':
    r = input('what is the radius?\n')
    r = int(r)
    c = Circle()
    print(c.circle(r))
  elif x.lower() == 'cube':
    l = input('What is the side legnth?\n')
    l = int(l)
    x = Rectangles()
    print(x.cube(l))
  elif x.lower() == 'rectangular prism':
    l = input('What is the length?\n')
    w = input('What is the width?\n')
    h = input('What is the height?\n')
    l = int(l)
    h = int(h)
    w = int(w)
    x = Rectangles()
    print(x.rectangular_prism(l, w, h))
  elif x.lower() == 'pyramid':
      l = input('What is the length?\n')
      w = input('What is the width?\n')
      h = input('What is the height?\n')
      l = int(l)
      h = int(h)
      w = int(w)
      p = Rectangles()
      print(p.pyramid(w, l, h))
  elif x.lower() == 'cone':
      r = input('What is the radius?\n')
      h = input('What is the height?\n')
      r = int(r)
      h = int(h)
      x = Circle
      print(x.cone(r, h))
  elif x.lower() == 'cylinder':
      r = input('What is the radius?\n')
      h = input('What is the height?\n')
      r = int(r)
      h = int(h)
      x = Circle
      print(x.cylinder(r, h))
  elif x.lower() == 'stop':
    break
  else:
    print('That is not a shape I can solve. Please enter rectangle, triangle, circle, cube, rectangular prisim, pyramid, cylinder,\nor cone.')

