# -*- coding: utf-8 -*-
"""Geometric_calc_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zr6TgbAkiLX8KXeCYjCPQyd6TDI6jUEM
"""

import math

"""##Formulas"""

def rectangle(legnth, width):
  rec_area = legnth * width
  rec_perimeter = 2 * legnth + 2 * width
  return f'The area is {rec_area}, and the perimeter is {rec_perimeter}'

def triangle_area(base, height):
  tri_area = base * height /2
  return f'The area is {tri_area}.'

def triangle_perimeter(side_1, side_2, side_3):
  tri_perimeter = side_1 + side_2 + side_3
  return f'The perimeter is {tri_perimeter}.'

def cube(legnth):
  cube_area = legnth ** 3
  cube_surface_area = 6 * legnth ** 2
  return f'The volume is {cube_area}, and the perimeter is {cube_surface_area}.'

def circle(radius):
  circ_diamater = radius * 2
  circ_circumferance = 2 * 3.14 * radius
  circ_area = 3.14 * radius ** 2
  return f'The diamater is {circ_diamater}, the circumferance is {circ_circumferance}, and the area is {circ_area}.'

def sphere(radius):
  sphere_surface_area = 4 * 3.14* radius ** 2
  sphere_volume = 4/3 * 3.14 * radius ** 3
  sphere_diamater = radius * 2
  return f'The diamter is {sphere_diamater}, the surface area is {sphere_surface_area}, and the volume is {sphere_volume}.'

def cone (radius, height):
  cone_slant = math.sqrt( radius ** 2 + height ** 2)
  cone_surface_area = 3.14 * radius * (radius + cone_slant)
  cone_volume = 3.14 * radius ** 2 * height / 3
  cone_area = 3.14 * radius ** 2
  cone_circumferance = 2 * 3.14 * radius
  return f'The area of the base is {cone_area}, and the circumferance of the base is {cone_circumferance}. The surface area of the cone is {cone_surface_area}, the volume of the cone is {cone_volume}, and the slant is {cone_slant}.'

def rectangular_prism(legnth, width, height):
  recp_surface_area = 2 * (legnth * width + legnth * height + height * width)
  recp_volume = width * legnth * height
  recp_space_diagonal = math.sqrt(legnth ** 2 + width ** 2 + height ** 2)
  return f'The surface area is {recp_surface_area}, the volume is {recp_volume}, and the space diagonal is {recp_space_diagonal}.'

def cylinder(radius, height):
  cyl_surface_area = 2 * radius * 3.14 * height + 2 * 3.14 * radius ** 2
  cyl_volume = 3.14 * radius ** 2 * height
  cyl_lateral_surface = 2 * 3.14 * radius * height
  cyl_base_area = 3.14 * radius ** 2
  cyl_diameter = 2 * radius
  return f'The diameter is {cyl_diameter}, and the base area is {cyl_base_area}. The volume is {cyl_volume}, the surface area is {cyl_surface_area}, and the lateral surface is {cyl_lateral_surface}.'

def pyramid(base_width, base_legnth, pyramid_height):
  w = base_width 
  l = base_legnth
  h = pyramid_height
  pyr_surface_area = l * w + l * math.sqrt((w / 2) ** 2 + h ** 2 + w) * math.sqrt((l / 2) ** 2 + h ** 2)
  pyr_volume = l * w * h / 3
  pyr_lateral_surface_area = l * math.sqrt((w / 2) ** 2 + h ** 2 + w) * math.sqrt ((l / 2) ** 2 + h ** 2)
  pyr_base_area = l * w
  return f'The base area is {pyr_base_area}. The surface area is {pyr_surface_area}, the lateral surface area is {pyr_lateral_surface_area}, and the volume is {pyr_volume}.'

#incomplete
#finish
##def triangular_prism(base_side_1, base_side_2, base_side_3, height):
  a = base_side_1
  b = base_side_2
  c = base_side_3
  height = h
  volume = 1 / 4 * h math.sqrt(-a ** 4 + 2 * (a * b) ** 2 + 2 * (a *c) ** 2 -b ** 4 + 2 * (b * c) ** 2 - c ** 4)

"""#imput"""

x = str(input("What shape do you want to solve?\n"))
if x.lower == rectangle:
  print("Input the legnth and the width")

