# -*- coding: utf-8 -*-
"""intro_classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BgVZd8ZP0EgkdggCfCXc5DfiRP1OH37C
"""

list_of_didgets = [2, 1, 5, 7, 3, 8, 9, 8, 13]

list_of_didgets.append(2)

class Person():
  #Initalize class with name and birthyear
  def __init__(self, name, birthyear):
    self.name = name
    self.birthyear = birthyear
    #define greeting function
  def greeting(self):
    return f'Hello {self.name}.'
  def seconds(self):
    current_time = datetime.datetime.now
    current_year = current_time.year
    time = (current_time.year - self.birthyear) * 60 * 60 * 24 * 365.25
    return f'{self.name} you have been on the earth for {time} seconds.'

lindsey = Person('Lindsey', 2006)
#Show greeting
print(lindsey.greeting())
#Show seconds been on earth
seconds(lindsey)

corey = Person('Corey', 1976)

zorian = Person('Zorian', 2006)

calder = Person('Calder', 2005)

seconds(corey())

seconds(zorian())

seconds(calder())

import datetime
time = datetime.datetime.now()
print(time)

def date_diffrence(y_m_d, date_1 = True):
  date_1 = datetime.datetime.now
  date_2 = y_m_d
  diffrence = date_1 - date_2
  return f'The diffrence between the dates is {diffrence}.'

date_diffrence(2006/2/3)

