# -*- coding: utf-8 -*-
"""Lindsey Soller Python_Review_Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZefpeYkK8Em6FoonPL3l1Uy38sw85qFt

# Functions - Ints, Floats, Strings
"""

# 1. Write a function that converts inches to feet that inlcudes labels in the output.
def inches_to_feat(inches):
  foot = inches / 12
  print(f'feet = {foot}')

inches_to_feat(48)

# 2. Write a function that takes a string as input and returns the same string with all capital letters and an exclamation at the end.
def captiol(string):
  all_capitol = string.upper() + '!'
  return all_capitol

captiol('dogs are the best')

# 3a. Write a function that returns the length, square, cube, and hypercube of a given input. Include labels.
# 3b. Find two examples to show that the order from largest to smallest can be reversed depending on the input.
def ultra_cube(num):
  square = num ** 2
  cube = num ** num
  hypercube = num ** num ** num ** num
  print(f'Legnth is {num}, squared is {square}, cubed is {cube}, and hypercubed is {hypercube}')

ultra_cube(2)

ultra_cube(.5)

ultra_cube(.25)

# 4a. Find 10 to the 500 power using Python
# 4b. Try to find 9.9 to the 500th power using Python
10 ** 500

9.9 ** 500

# 5. Write a function that divides two numbers and shows the result, including any remainder. 
def devide(num_1, num_2):
  return num_1 / num_2

devide(10, 3)

"""# Functions - Lists, Loops, Dictionaries"""

# 6. Display the first 33 multiples of 3.

# 7. Sum all multiples of 4 between 20 and 100.

# 8. Write a function that takes a list of ints and converts them to a list of floats.

# 9. Write a function that a takes a dictionary as input with student names as keys and test scores as values. 
# Return the average test score.

# 10. Write a function that prints out every index in a list.

"""# Extra Practice"""

# 11. Write a function that returns the factorial of a number. For example, factorial(5) should return 5 * 4 * 3 * 2 * 1.

# 12. Write a function that takes a verb as input and returns a sentence.

# 13. Create an empty dictionary called seconds. Add your name and age in seconds. Add 2 other people with different ages.

# 14. Write a function that finds the third length of a right triangle given the other 2.

# 15. Write a function that gives the area of a cirle. Allow the user to choose pi or a decimal approximation.

# 16. Write a function that reverses a string.

# 17. Write a function that determines if a number is a palindrome (reads same forward and backward).

# 18. Given two points, return the equation of the line.

# 19. Write a function that tells whether a given number is prime. If it's not prime, give it's factors.

# 20a. Play a guessing game with the user. The computer chooses a number between 0 and 100. 
# If the number is too high, or too low, let the user know.

# 20b. Play a guessing game with the computer. You choose a number beteen 0 and 100.
# Allow the computer to guess. Let the computer know if it's too high or low. Provide a strategy so the computer can win.